### ISSUE TITLE
Add VAPID functionality

### ISSUE THREAD

**Issue by groovecoder** [mozilla/wp-web-push#120]
Add optional functionality to append [VAPID](https://tools.ietf.org/html/draft-thomson-webpush-vapid-02) to push messages sent by wp-web-push to push servers.

**Comment by groovecoder** [comment]
@marco-c - I'd like to get this going so we can test PHP-generated VAPID keys with the dashboard. Do you have time for this, or should I start on it? (I only ask because my PHP coding is _very_ rusty so I'm probably not the best person to tackle this.)

**Comment by marco-c** [comment]
Hey Luke, I will investigate tomorrow. For payloads, it's quite hard because PHP doesn't support a lot of the needed functionality (e.g. https://bugs.php.net/bug.php?id=61204 and https://bugs.php.net/bug.php?id=67304), so you have to use external libraries (that aren't really secure as far as I know).

**Comment by groovecoder** [comment]
Ah, yeah I was poking around packagist.org and I found https://packagist.org/packages/lcobucci/jwt ... which seems to have the elliptic curve code. That was as far as I got looking for something and then I realized I might punt it to you. :wink:
